# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Customized Cloud Storage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Customized Cloud Storage
  pod ‘Toast-Swift’, ‘~> 2.0’

  target 'Customized Cloud StorageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Customized Cloud StorageUITests' do
    inherit! :search_paths
    # Pods for testing
    pod ‘Toast-Swift’, ‘~> 2.0’
  end

end
